"""check_no_allow.py — policy tests, including the stated-vs-implemented
exemption window (docstring says "first 40 lines"; HEAD implements 2000 chars;
Phase 3 aligns the code to the docstring)."""

from conftest import commit_all, run_check, stage, write

SCRIPT = "checks/check_no_allow.py"

ALLOW = "#[allow(dead_code)]\nfn f() {}\n"
INNER = "#![allow(clippy::all)]\n"


def _mkcrate(repo):
    (repo / "src").mkdir(exist_ok=True)
    return repo / "src"


def test_allow_in_src_fails(repo):
    (_mkcrate(repo) / "lib.rs").write_text(ALLOW, encoding="utf-8")
    commit_all(repo)
    r = run_check(repo, SCRIPT)
    assert r.returncode == 1
    assert "lib.rs" in r.stdout


def test_inner_attribute_also_fails(repo):
    (_mkcrate(repo) / "lib.rs").write_text(INNER, encoding="utf-8")
    commit_all(repo)
    assert run_check(repo, SCRIPT).returncode == 1


def test_expect_is_permitted(repo):
    # #[expect] errors if its lint never fires — the allow that cannot rot.
    (_mkcrate(repo) / "lib.rs").write_text(
        '#[expect(dead_code, reason = "pending")]\nfn f() {}\n',
        encoding="utf-8",
    )
    assert run_check(repo, SCRIPT).returncode == 0


def test_tests_dir_out_of_scope(repo):
    # tests/ may unwrap; clippy --all-targets still polices warnings there.
    t = repo / "tests"
    t.mkdir(exist_ok=True)
    (t / "it.rs").write_text(ALLOW, encoding="utf-8")
    commit_all(repo)
    assert run_check(repo, SCRIPT).returncode == 0


def test_build_rs_in_scope(repo):
    (repo / "build.rs").write_text("// x\n#[allow(dead_code)]\n", encoding="utf-8")
    commit_all(repo)
    assert run_check(repo, SCRIPT).returncode == 1
    nested = repo / "crates" / "sub"
    nested.mkdir(parents=True, exist_ok=True)
    (nested / "build.rs").write_text("#[allow(unused)]\n", encoding="utf-8")
    commit_all(repo)
    assert run_check(repo, SCRIPT).returncode == 1


def test_generated_marker_within_40_lines_exempt(repo):
    p = _mkcrate(repo) / "gen.rs"
    head = "\n".join(["// scaffold"] * 39 + ["// @generated by prost"]) + "\n"
    p.write_text(head + ALLOW, encoding="utf-8")
    commit_all(repo)
    assert run_check(repo, SCRIPT).returncode == 0


def test_marker_after_line_40_does_not_exempt(repo):
    # The documented window is 40 LINES. A marker on line 41 must not exempt
    # an #[allow] sitting above it.
    p = _mkcrate(repo) / "late.rs"
    body = ALLOW + "\n".join(["// filler"] * 41 + ["// @generated later"]) + "\n"
    p.write_text(body, encoding="utf-8")
    commit_all(repo)
    assert run_check(repo, SCRIPT).returncode == 1


def test_staged_scope(repo):
    p = _mkcrate(repo) / "new.rs"
    p.write_text(ALLOW, encoding="utf-8")
    stage(repo, "src/new.rs")
    assert run_check(repo, SCRIPT, "--staged").returncode == 1


# ---- conservative comment-awareness (2026-08-25) ------------------------------
#
# A doc-comment MENTIONING #[allow] is prose about the policy, not a
# suppression. Whole-line // comments (incl. /// and //!), and /* */ spans
# tracked across lines, are skipped. Code lines are searched WHOLE — a real
# attribute behind a trailing comment still flags; that errs safe.


def test_doc_comment_mention_passes(repo):
    (_mkcrate(repo) / "lib.rs").write_text(
        "/// Never write #[allow(dead_code)] in this crate.\n"
        "fn f() {}\n"
        "// TODO: audit the #[allow(unused)] in legacy modules\n"
        "//! Crate docs may discuss #![allow(clippy::all)] freely.\n",
        encoding="utf-8",
    )
    commit_all(repo)
    r = run_check(repo, SCRIPT)
    assert r.returncode == 0, r.stdout


def test_multiline_block_comment_mention_passes(repo):
    (_mkcrate(repo) / "lib.rs").write_text(
        "/* This module deliberately contains no\n"
        "   #[allow(dead_code)] anywhere;\n"
        "   see the lint policy. */\n"
        "fn g() {}\n"
        "/* a block comment opening that keeps going\n"
        "   with #[allow(unused_mut)] inside */\n"
        "fn h() {}\n",
        encoding="utf-8",
    )
    commit_all(repo)
    assert run_check(repo, SCRIPT).returncode == 0


def test_real_allow_after_block_comment_still_fails(repo):
    (_mkcrate(repo) / "lib.rs").write_text(
        "/* prose about #[allow(dead_code)] */\n" + ALLOW,
        encoding="utf-8",
    )
    commit_all(repo)
    assert run_check(repo, SCRIPT).returncode == 1


def test_allow_on_code_line_with_trailing_comment_still_fails(repo):
    # Accepted conservatism: code lines are searched whole, so a mention in a
    # trailing comment on a CODE line flags too — errs safe.
    (_mkcrate(repo) / "lib.rs").write_text(
        "fn f() {} // mirrors the removed #[allow(dead_code)]\n"
        "#[allow(dead_code)] fn real() {}\n",
        encoding="utf-8",
    )
    commit_all(repo)
    assert run_check(repo, SCRIPT).returncode == 1


def test_string_containing_url_is_untouched(repo):
    (_mkcrate(repo) / "lib.rs").write_text(
        'const DOC: &str = "see http://example.com/allow-guide";\n'
        'const URLS: [&str; 2] = ["https://a.dev", "http://b.test"];\n',
        encoding="utf-8",
    )
    commit_all(repo)
    assert run_check(repo, SCRIPT).returncode == 0


# ---- depth-counter block-comment scan (2026-08-26) -----------------------------
#
# The split-based detector ignored a SECOND /* opener on one line (flagging
# comment-only mentions) and skipped a whole line containing a same-line */
# close (missing a REAL #[allow] after it). A per-line depth counter fixes
# both; these are its red-proven regressions.


def test_second_opener_on_one_line_reenters_comment(repo):
    # /* closed */ code /* reopened, runs on — the OLD detector judged
    # block state from the first opener only, so lines under the SECOND,
    # unterminated span were searched and a comment-only mention flagged.
    (_mkcrate(repo) / "lib.rs").write_text(
        "/* closed */ fn ok() {} /* reopened, keeps going\n"
        "#[allow(dead_code)] inside prose\n"
        "*/\n"
        "fn f() {}\n",
        encoding="utf-8",
    )
    commit_all(repo)
    r = run_check(repo, SCRIPT)
    assert r.returncode == 0, r.stdout


def test_real_allow_after_same_line_close_flags(repo):
    # A line carrying the close of an open block AND a real attribute was
    # skipped wholesale (was a false negative).
    (_mkcrate(repo) / "lib.rs").write_text(
        "/* policy prose opens\n"
        "*/ #[allow(dead_code)]\n"
        "fn f() {}\n",
        encoding="utf-8",
    )
    commit_all(repo)
    r = run_check(repo, SCRIPT)
    assert r.returncode == 1
    assert "lib.rs:2" in r.stdout


def test_unterminated_block_to_eof_is_safe(repo):
    # No closer anywhere: everything after the opener stays comment; no
    # crash, no flag.
    (_mkcrate(repo) / "lib.rs").write_text(
        "fn ok() {}\n"
        "/* never closed\n"
        "#[allow(dead_code)]\n",
        encoding="utf-8",
    )
    commit_all(repo)
    r = run_check(repo, SCRIPT)
    assert r.returncode == 0, r.stdout


def test_nested_block_comments_track_depth(repo):
    # Swift-style nesting is not Rust, but a depth counter handles it for
    # free and must not resync early on the first inner */.
    (_mkcrate(repo) / "lib.rs").write_text(
        "/* outer /* inner */ still outer with #[allow(dead_code)] */\n"
        "fn f() {}\n",
        encoding="utf-8",
    )
    commit_all(repo)
    r = run_check(repo, SCRIPT)
    assert r.returncode == 0, r.stdout
