//! Unit tests for `noallow` (split out for the line cap).

use super::*;

fn scanner() -> Scanner {
    Scanner::compile().expect("built-in patterns compile")
}

// The fixtures below are BUILT, never spelled: this file is policed by
// its own check, and a suppression written inside a string literal
// fires (the conservative policy the reference keeps). Until 2026-09-23
// a backticked mention of the generated marker in the module doc
// exempted the whole file, which hid exactly these lines.
const ALLOW: &str = "allow";
const EXPECT: &str = "expect";

/// `#[kind(body)]`, or `#![kind(body)]` for an inner attribute.
fn attr(inner: bool, kind: &str, body: &str) -> String {
    format!("#{}[{kind}({body})]", if inner { "!" } else { "" })
}

/// `#[cfg_attr(cfg, wrapped)]`.
fn cfg_attr(cfg: &str, wrapped: &str) -> String {
    format!("#[{}({cfg}, {wrapped})]", "cfg_attr")
}

#[test]
fn literal_suppressions_fire() {
    let sc = scanner();
    for line in [
        attr(false, ALLOW, "dead_code"),
        attr(true, ALLOW, "clippy::all"),
        attr(false, EXPECT, "dead_code"),
        format!("    {}", attr(true, EXPECT, "unused")),
    ] {
        assert_eq!(sc.scan_code(&line).len(), 1, "{line}");
    }
}

#[test]
fn doc_comments_are_prose_not_suppressions() {
    let sc = scanner();
    let text = format!(
        "/// Mentioning {} is prose.\nfn f() {{}}\n/* {} */\n",
        attr(false, ALLOW, "dead_code"),
        attr(false, EXPECT, "x")
    );
    assert!(sc.scan_code(&text).is_empty());
    // A real attribute after a same-line block close still fires.
    assert_eq!(
        sc.scan_code(&format!("/* note */ {}", attr(false, ALLOW, "x")))
            .len(),
        1
    );
}

#[test]
fn nested_block_comments_carry_state() {
    let sc = scanner();
    let text = format!(
        "/* outer /* inner */ {}\nmore\n*/\n{}\n",
        attr(false, ALLOW, "x"),
        attr(false, ALLOW, "y")
    );
    let hits = sc.scan_code(&text);
    assert_eq!(hits.len(), 1);
    assert_eq!(hits[0].0, 4);
}

#[test]
fn cfg_attr_wrapped_suppressions_fire() {
    let sc = scanner();
    let macos = "target_os = \"macos\"";
    assert_eq!(
        sc.scan_code(&cfg_attr(macos, &format!("{EXPECT}(unsafe_code)")))
            .len(),
        1
    );
    // Multi-line rustfmt layout: the token on the continuation line.
    let text = format!(
        "#[{}(\n    {macos},\n    {ALLOW}(dead_code),\n)]\n",
        "cfg_attr"
    );
    assert_eq!(sc.scan_code(&text).len(), 1);
    // cfg_attr without a suppression passes.
    assert!(sc.scan_code(&cfg_attr(macos, "must_use")).is_empty());
    // A path or a longer identifier is not a suppression.
    assert!(sc
        .scan_code(&cfg_attr("x", &format!("cfg::{ALLOW}(y)")))
        .is_empty());
    assert!(sc.scan_code("let allow_x = 1;").is_empty());
}

#[test]
fn string_mentions_do_not_fire_for_wrapped_form() {
    let sc = scanner();
    // The reference blanks string literals ONLY for the wrapped
    // (`cfg_attr`) search — a literal `#[allow(` inside a string still
    // fires there, and so does here (verified against the checker).
    let quoted_allow = format!("let s = \"{}\";", attr(false, ALLOW, "x"));
    assert_eq!(sc.scan_code(&quoted_allow).len(), 1);
    assert!(sc
        .scan_code(&cfg_attr("x", &format!("\"{ALLOW}(y)\"")))
        .is_empty());
}

/// A `cfg_attr` spelled inside a string is judged on its own line and
/// never carried: a later `.expect(` is not inside any attribute.
#[test]
fn a_quoted_cfg_attr_does_not_stay_open() {
    let sc = scanner();
    let text = format!(
        "let s = \"{}\";\nlet v = w.{EXPECT}(\"fixture\");\n",
        cfg_attr("test", &format!("{ALLOW}(x)"))
    );
    let hits = sc.scan_code(&text);
    assert_eq!(hits.iter().map(|h| h.0).collect::<Vec<_>>(), vec![1]);
}

#[test]
fn a_documented_marker_is_not_the_marker() {
    assert!(is_generated("// @generated by a tool\nfn f() {}\n"));
    assert!(!is_generated(
        "//! Files carrying `@generated` are exempt.\nfn f() {}\n"
    ));
}

#[test]
fn scope_and_verdicts() {
    assert!(is_compiled_src("src/a.rs"));
    assert!(is_compiled_src("crates/x/tests/f.rs"));
    assert!(is_compiled_src("build.rs"));
    assert!(is_compiled_src("a/build.rs"));
    assert!(!is_compiled_src("tools/a.rs"));
    // Path scope only — the `.rs` suffix filter lives in `scan_root`,
    // mirroring the reference split between `_files` and
    // `_is_compiled_src`.
    assert!(is_compiled_src("src/a.py"));
    assert_eq!(classify(2, 3, true), ScopeVerdict::Violations);
    assert_eq!(classify(0, 0, true), ScopeVerdict::BlindLayout);
    assert_eq!(classify(0, 0, false), ScopeVerdict::Clean);
    assert_eq!(classify(0, 5, true), ScopeVerdict::Clean);
}

#[test]
fn generated_marker_exempts_within_forty_lines() {
    let head = (0..39)
        .map(|i| format!("// {i}"))
        .collect::<Vec<_>>()
        .join("\n");
    assert!(scan_text(
        &scanner(),
        "f.rs",
        &format!("{head}\n// @generated\n#[allow(x)]")
    )
    .is_empty());
    let head = (0..40)
        .map(|i| format!("// {i}"))
        .collect::<Vec<_>>()
        .join("\n");
    assert_eq!(
        scan_text(
            &scanner(),
            "f.rs",
            &format!("{head}\n// @generated\n#[allow(x)]")
        )
        .len(),
        1
    );
}
